name: Test Python CLI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/cli-py/**'
      - 'packages/core/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'packages/cli-py/**'
      - 'packages/core/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd packages/cli-py
          pip install -e .
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          cd packages/cli-py
          pytest tests/ --cov=paws --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/cli-py/coverage.xml
          flags: python-cli
